---
exclude: "index.json|^themes/"
fail_fast: true
repos:
  - hooks:
      - id: commitizen
        stages:
          - commit-msg
    repo: https://github.com/commitizen-tools/commitizen
    rev: 3.6.0
  - hooks:
      - id: check-useless-excludes
    repo: meta
  - hooks:
      - files: \.(css|js|md|markdown|json)
        id: prettier
    repo: https://github.com/pre-commit/mirrors-prettier
    rev: v3.0.2
  - hooks:
      - id: seed-isort-config
    repo: https://github.com/asottile/seed-isort-config
    rev: v2.2.0
  - hooks:
      - id: isort
    repo: https://github.com/pre-commit/mirrors-isort
    rev: v5.10.1
  - hooks:
      - id: black
    repo: https://github.com/python/black
    rev: 23.7.0
  - hooks:
      - id: check-added-large-files
        args: [--maxkb=10000]
      - id: check-ast
      - id: check-case-conflict
      - id: check-executables-have-shebangs
      - id: check-json
      - id: check-merge-conflict
      - id: check-symlinks
      - id: check-vcs-permalinks
      - id: debug-statements
      - id: check-xml
      - args:
          - --unsafe
        id: check-yaml
      - id: end-of-file-fixer
      - id: forbid-new-submodules
      - args:
          - --branch
          - gh-pages
        id: no-commit-to-branch
      - id: requirements-txt-fixer
      - id: sort-simple-yaml
      - id: trailing-whitespace
      - id: mixed-line-ending
      - id: detect-private-key
      - id: check-byte-order-marker
      - id: check-docstring-first
    repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
  - hooks:
      - id: flake8
    repo: https://github.com/pycqa/flake8
    rev: 6.1.0
  - repo: https://github.com/scop/pre-commit-shfmt
    rev: v3.7.0-1
    hooks:
      # Choose one of:
      - id: shfmt # native (requires/installs Go to build)

    types:
      - shell

  - hooks:
      - id: blacken-docs
    repo: https://github.com/asottile/blacken-docs
    rev: 1.16.0

  # - repo: https://github.com/asottile/pyupgrade
  #   rev: v2.38.0
  #   hooks:
  #     - id: pyupgrade
  #       args: [--py39-plus]

  - repo: https://github.com/jumanjihouse/pre-commit-hook-yamlfmt
    rev: 0.2.3 # or other specific tag
    hooks:
      - id: yamlfmt
        args: [--mapping, "2", --sequence, "4", --offset, "2", "--preserve-quotes"]

  - repo: https://github.com/hcodes/yaspeller.git
    rev: v8.0.1
    hooks:
      - id: yaspeller
        files: \.en\.md
        types:
          - markdown
